
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_plus?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=GMT%2B8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  profiles:
    active: dev # 开发环境

#mybatisplus 日志打印，控制台输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #控制台输出
  global-config:
    db-config:
      logic-delete-value: 1      #表示删除
      logic-not-delete-value: 0  #表示未删除
      logic-delete-field: deleted #字段

